"""add carts table and cart items relationship

Revision ID: 9ba1078ca3c0
Revises: 0b88dda0ece9
Create Date: 2026-08-31 17:30:23.268330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba1078ca3c0'
down_revision: Union[str, Sequence[str], None] = '0b88dda0ece9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'cart_items', 'Carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cart_items', 'cart_id')
    op.drop_table('Carts')
    # ### end Alembic commands ###
