"""align existing schema

Revision ID: ce11ede30bc7
Revises: 
Create Date: 2026-08-30 23:56:01.943867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce11ede30bc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('Users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('contact', sa.String(), nullable=True))
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'contact')
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'hashed_password')
    op.drop_column('Users', 'username')
    op.alter_column('Products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
